Amazon IVS Player React sample app
aws-samples/amazon-ivs-player-web-sample pull request #22
Opened 2021-03-17 20:15 UTC by neer300

*Issue #, if available:*

*Description of changes:*
A demo app showing usage of react with Amazon IVS Player

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-18 15:57 UTC, johnBartos requested changes
A bit out of my wheelhouse but I read up on the React docs. Two overall pieces of feedback:

* Consider removing the unnecessary creat-react-app boilerplate
* Maybe we should get a review from someone with React experience

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/README.md
> +AmazonIVSPlayerComponent - This component shows how to wrap Amazon IVS Player sdk using <script> approach. A unique player instance is associated for a component and is deleted when the component is
Some grammar:

This component shows how to wrap **the** Amazon IVS Player using **the** <script> **tag** approach. A unique player instance is associated for **each** component and is deleted when the component is unmounted.

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/README.md
> +In the project directory, you can run:
~~In~~ From the project directory, you can run:

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/App.js
> +  // const [currentSrc, setCurrentSrc] = useState('https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.xhP3ExfcX8ON.m3u8');
Should probably remove this comment

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/App.test.js
> +  const linkElement = screen.getByText(/learn react/i);
Should we add some real tests? I don't think keeping this is useful

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +// import * as AmazonIVSPlayer from 'amazon-ivs-player';
Should probably remove this

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +export default AmazonIVSPlayerComponent;
Need to add a newline here

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +import React, { useEffect, useRef, useState } from 'react'
In general I think this file needs more comments which explains why this approach is good for the IVS player. I know that we want to instruct developers to re-use instances, but it's not clear that that is the guidance

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +    }, [vEl.current, player]);
When are these functions called? I read the hooks API and it seems like these are executed whenever the DOM component updates. Will we accidentally be re-loading the player when we don't intend to? Should these only be called once like the third hook?

2021-03-18 15:57 UTC, johnBartos commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +            s.src = "https://player.live-video.net/1.2.0/amazon-ivs-player.min.js"
Just curious why we do this here instead of in index.js

2021-03-19 20:46 UTC, closed without merging

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/App.js
> +      <ToggleButton show={false} onClick={setShowPlayer}></ToggleButton>
setShowPlayer will be called with event args, but its boolean type. Probably should create a handler that calls setShowPlayer with boolean?

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/App.js
> +  const [srcList, setSrcList] = useState(['https://fcc3ddae59ed.us-west-2.playback.live-video.net/api/video/v1/us-west-2.893648527354.channel.xhP3ExfcX8ON.m3u8']);
Default can be referenced directly from the list than duplicated

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +const AmazonIVSPlayerComponent = React.forwardRef((props, ref) => {
forwardRef needed? Since nothing is being forwarded from App

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/amazon-ivs-player-react-component/index.js
> +    const [player, setPlayer] = useState(null);
Player is a complex object, should ideally just be a local variable, look at useRef for it if you want to keep its reference. Making it part of state is useful if you want to cause a re-render of the component, is that desired?

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/toggle-button/index.js
> +import React, { useState } from 'react';
Normally I keep logic out of index files in general. And only use index.js to export.

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/url-box/index.js
> +        props.submitHandler(inputEl.current.value);
Needs some validation here for bogus entries?

2021-03-19 21:17 UTC, priyajeet commented on samples/react-ivs-script/src/toggle-button/index.js
> +        <button onClick={clickHandler}>
type="button"

2021-03-19 21:38 UTC, priyajeet commented on samples/react-ivs-script/yarn.lock
> +  resolved "https://npm.pkgs.xarth.tv:443/artifactory/api/npm/vr-npm/@babel/runtime/-/runtime-7.13.10.tgz#47d42a57b6095f4468da440388fdbad8bebf0d7d"
internal urls
You should add a .npmrc and a .yarnrc to this project that points to public npmjs and yarn registry respectively

2021-03-19 21:56 UTC, priyajeet commented on samples/react-ivs-script/src/toggle-button/index.js
> +    const [show, setShow] = useState(props.show);
I think this component can be stateless, since the parent is keeping a boolean of show/hide. Maybe just pass that down here and use as-is